### ISSUE TITLE
Info: My first Xiangqi tournament with Fairy-Stockfish

### ISSUE THREAD

**Issue by nguyenpham** [fairy-stockfish/Fairy-Stockfish-NNUE#14]
AMD Ryzen 7 1700 Eight-Core Processor
64 MB Hash
Timer: 40/300+1
Total 200 games Roundrobin
GUI: MoonRiver

Fairy-Stockfish classic is one running without NNUE.

The good news is that Fairy-Stockfish beat GG Chess and SA Chess - two Xiangqi engines were strong and famous and they had commercial versions with a significantly large margin.

The weird thing is that the classic one is stronger than the NNUE one!

![mr01](https://user-images.githubusercontent.com/1370755/209120342-d6291669-0c4c-459d-a5c5-0bb11247d871.png)

**Comment by ianfab** [comment]
Thanks. There must be an issue with your setup then though. It might be that the "classical" also uses NNUE guessing from the results. NNUE should be at least 500 Elo stronger than classical for Xiangqi.

**Comment by nguyenpham** [comment]
New result of a new tournament. Options to Fairy-Stockfish are verified (it is only one using UCCI). None of games are crashed or timeout. Look like strengths of Classic and NNUE are now reasonable!

![mr04](https://user-images.githubusercontent.com/1370755/209242513-217f0d47-2ff7-472e-8acb-bc58d88de75b.PNG)
